### ISSUE TITLE
Not possible in combination with nextjs

### ISSUE THREAD

**Issue by nealoke** [react-native-web-community/react-native-web-maps#24]
I've spent 2 days figuring out why it doesn't work even though the alias is added in my `.babelrc` as well as in my `next.config.js` files. 

I initially thought it was another issue which you can view on [stackoverflow](https://stackoverflow.com/questions/58059091/unable-to-resolve-alias-in-sibling-folder-using-for-nextjs-project) where you can see my files that I used.

The error you receive is that it cannot find `warnOnce` (even though the aliases are provided and working for other parts of the application)

**Comment by nonotest** [comment]
Hey,

works by adding

```
 webpack: config => {
        config.resolve.alias = {
          ...(config.resolve.alias || {}),
          'react-native-maps$': 'react-native-web-maps'
        }
        return config
      }
```
to your config
