### ISSUE TITLE
Setting mapstyle (ie. satellite)

### ISSUE THREAD

**Issue by jasperbeckers** [react-native-web-community/react-native-web-maps#25]
Is this possible to be added?

**Comment by Entryist** [comment]
You can pass a custom map style into the options prop. See [react-google-maps reference docs](https://tomchentw.github.io/react-google-maps/#usage--configuration), search "Styled Map".

```
<MapView
  initialRegion={{
    latitude: 37.78825,
    longitude: -122.4324,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }}
  options={{ styles: gmapstyle }}
/>
```

**Comment by jasperbeckers** [comment]
Thank you veyr much, I was not aware of the options parameter. I will close this issue.
