### ISSUE TITLE
Setup help.

### ISSUE THREAD

**Issue by cfchacon10** [react-native-web-community/react-native-web-maps#27]
I am sorry to have to ask for help, but I am new to React Native. React Native project apps do not use an index.html file. I was just wondering where everyone was creating and placing this file in their project folders. I am using Expo.

**Comment by theZulqarnain** [comment]
Run `expo customize:web` to generate index.html

**Comment by vrinch** [comment]
Hello @cfchacon10 did it work for you in expo?
Because I am also using expo and I haven’t gotten around to making it work

**Comment by mmaass** [comment]
I had to run `npx expo customize`, select web/index.html, press space, press enter to generate the file.

found this solution [here](https://github.com/expo/expo-cli/issues/4319)
