### ISSUE TITLE
MapView.Polyline not working

### ISSUE THREAD

**Issue by theZulqarnain** [react-native-web-community/react-native-web-maps#30]
In my Android app it drawing the polyline but it not functioning in Web. I could not found any example even in that storybook. please can share an example. I'm stuck in middle :)

**Comment by kopax** [comment]
DId you try setting fome height or flex on your inner views?

**Comment by ysfzrn** [comment]
You must implement like react-google-maps. You can check [this](https://stackoverflow.com/a/52503089) example.

`<MapView.Polyline path={coordinates} />`
