### ISSUE TITLE
API Key not defined

### ISSUE THREAD

**Issue by pirminb97** [react-native-web-community/react-native-web-maps#6]
Im searching for a way to have the API Key shared in one file for the native and PWA.

This was my approach:

in App.web.js:

```
<View style={styles.container}>
        <Helmet>
          <script
            src={`https://maps.googleapis.com/maps/api/js?key=${Config.GOOGLE_MAPS_API_KEY}`}
          />
        </Helmet>
...
</View>
```
instead of importing it to index.html, im sharing it between PWA and Native in the "Config" file.

at first it worked but warned, that key is used duplicated.

`Google Maps JavaScript API error: DeletedApiProjectMapError`

now the key has been deleted by google maps because of duplication:

`Make sure you've put a <script> tag in your <head> element to load Google Maps JavaScript API v3.`

Im wondering if there is any solution for this...

**Comment by pirminb97** [comment]
fixed it myself by loading script in the component

**Comment by CorinneKelly** [comment]
@pirminb97 can you share your solution?
